services:
  db:
    image: postgres:latest
    container_name: t3_demo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: t3_demo
      volumes: docker pull $IMAGE
        - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
